### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by MCCasper** [RyseInventory/RyseInventory#55]
**Describe the bug**
When placing an item, a ConcurrentModificationError occurs.

**To Reproduce**
1. Create a redraw function
2. Call the redraw function in your init function
3. Call the updateOrSet function while iterating over your config items
4. Get a ConcurrentModificationException

**Expected behavior**
The menu opens & no concurrent modification error is sent.

**Code (Optional)**
My code is just wrappers for placing items using InventoryContents#updateOrSet

**Screenshots**
N/A

**Additional context**

java.util.ConcurrentModificationException: null
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1604) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at io.github.rysefoxx.inventory.plugin.pagination.Pagination.get(Pagination.java:365) ~[paper-amethyst-1.0-SNAPSHOT.jar:?]
        at io.github.rysefoxx.inventory.plugin.pagination.Pagination.get(Pagination.java:327) ~[paper-amethyst-1.0-SNAPSHOT.jar:?]
        at io.github.rysefoxx.inventory.plugin.content.InventoryContents.get(InventoryContents.java:2558) ~[paper-amethyst-1.0-SNAPSHOT.jar:?]
        at io.github.rysefoxx.inventory.plugin.content.InventoryContents.updateOrSet(InventoryContents.java:466) ~[paper-amethyst-1.0-SNAPSHOT.jar:?]
        at wtf.casper.amethyst.paper.menu.AmethystMenu.placeItem(AmethystMenu.java:209) ~[paper-amethyst-1.0-SNAPSHOT.jar:?]
        at wtf.casper.lifesteal.fork.BeaconOfLifeMenu.redraw(BeaconOfLifeMenu.java:105) ~[lifesteal-1.0-SNAPSHOT.jar:?]
        at wtf.casper.lifesteal.fork.BeaconOfLifeMenu.initJava(BeaconOfLifeMenu.java:59) ~[lifesteal-1.0-SNAPSHOT.jar:?]
        at wtf.casper.amethyst.paper.menu.AmethystMenu.init(AmethystMenu.java:74) ~[paper-amethyst-1.0-SNAPSHOT.jar:?]
        at io.github.rysefoxx.inventory.plugin.pagination.RyseInventory.initProvider(RyseInventory.java:1169) ~[paper-amethyst-1.0-SNAPSHOT.jar:?]

BeaconOfLife:105 is calling placeItem(Section, null, null, InventoryContents, null)
placeItem is a wrapper function to place items, the issue is not from this function.

I was able to come to the conclusion the issue is caused from different threads modifying the same slots at the same time.

**Comment by Rysefoxx** [comment]
> I was able to come to the conclusion the issue is caused from different threads modifying the same slots at the same time.

I see. The problem is apparently on your side then, if it only occurs then? I call methods from BukkitAPI inside my methods. Calling BukkitAPI methods must never be executed on Asynchronous. Try again on the main thread.

**Comment by MCCasper** [comment]
I think you misunderstand what I mean, I had my code setup more like...

CompletableFuture.whenComplete -> set the item // this when complete is pulling from a cache so in my code it was practically instant
set the item

This leads to a setup where I am running the whenComplete and the set item which both set the item at practically the same time. This leads to a concurrent modification error because (from what I know) the completable future runs off the main thread so the main thread and this completable future thread are trying to access the item at the same time. 

If this is an error thats on my end and cannot be prevented in the menu code then oh well.

**Comment by Rysefoxx** [comment]
Of course, you can customize something on your side and I can customize something on my side. I'll try to reproduce it and expand it further thread-safe.

**Comment by Rysefoxx** [comment]
Try the new version 1.5.7 and let me know if your problems are fixed.

**Comment by Rysefoxx** [comment]
Closed due to no response.
