### ISSUE TITLE
Pagination Bug

### ISSUE THREAD

**Issue by ch4ika** [RyseInventory/RyseInventory#64]
Cannot create filled content pagination.
As soon as I try to go to the next page, the given error comes up.

Error:

```
[15:47:05 WARN]: [Test] Task #39 for Test v1.0 generated an exception
java.lang.IllegalArgumentException: An attempt is made to place an item in slot -1. Check your pagination. If you could determine that it is not your error, report it on Github.
        at io.github.rysefoxx.inventory.plugin.pagination.RyseInventory.placeItem(RyseInventory.java:1049) ~[test-1.0-SNAPSHOT.jar:?]
        at io.github.rysefoxx.inventory.plugin.pagination.RyseInventory.lambda$load$21(RyseInventory.java:1035) ~[test-1.0-SNAPSHOT.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at io.github.rysefoxx.inventory.plugin.pagination.RyseInventory.load(RyseInventory.java:1035) ~[test-1.0-SNAPSHOT.jar:?]
        at io.github.rysefoxx.inventory.plugin.pagination.RyseInventory.loadDelay(RyseInventory.java:1259) ~[test-1.0-SNAPSHOT.jar:?]
        at io.github.rysefoxx.inventory.plugin.pagination.RyseInventory.initInventory(RyseInventory.java:692) ~[test-1.0-SNAPSHOT.jar:?]
        at io.github.rysefoxx.inventory.plugin.pagination.RyseInventory.lambda$open$8(RyseInventory.java:566) ~[test-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-527]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-527]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-527]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
package de.test;

import io.github.rysefoxx.inventory.plugin.content.IntelligentItem;
import io.github.rysefoxx.inventory.plugin.content.InventoryContents;
import io.github.rysefoxx.inventory.plugin.content.InventoryProvider;
import io.github.rysefoxx.inventory.plugin.pagination.InventoryManager;
import io.github.rysefoxx.inventory.plugin.pagination.Pagination;
import io.github.rysefoxx.inventory.plugin.pagination.RyseInventory;
import io.github.rysefoxx.inventory.plugin.pagination.SlotIterator;
import org.bukkit.Material;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.java.JavaPlugin;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class Test extends JavaPlugin implements CommandExecutor {

    private final InventoryManager inventoryManager = new InventoryManager(this);

    @Override
    public void onEnable() {

        inventoryManager.invoke();

        Objects.requireNonNull(getCommand("test")).setExecutor(this);

        inventoryManager.getLastInventory(null).ifPresent(inventory -> {

        });

    }

    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if(!(sender instanceof Player player)) {
            return true;
        }
        getPaginationInventory().open(player);
        return true;
    }

    private RyseInventory getPaginationInventory() {
        return RyseInventory.builder().title("Test").rows(6).disableUpdateTask().provider(new InventoryProvider() {
            @Override
            public void init(Player player, InventoryContents contents) {
                contents.fillBorders(IntelligentItem.empty(new ItemStack(Material.GRAY_STAINED_GLASS_PANE)));

                List<IntelligentItem> items = new ArrayList<>();
                for(int i = 0; i < 100; i++) {
                    items.add(IntelligentItem.of(new ItemStack(Material.BLUE_BED), event -> {
                        if(event.isLeftClick()) {
                            contents.updateMaterial(event.getSlot(), Material.RED_BED);
                            contents.updateDisplayName(event.getSlot(), "§aTest");
                        }
                    }));
                }

                Pagination pagination = contents.pagination();
                pagination.setItemsPerPage(28);
                pagination.iterator(SlotIterator.builder().startPosition(1, 1).type(SlotIterator.SlotIteratorType.HORIZONTAL).build());
                pagination.setItems(items);

                int previousPage = pagination.page() - 1;
                contents.set(5, 3, IntelligentItem.of(new ItemStack(Material.ARROW), event -> {
                    if (pagination.isFirst()) {
                        player.sendMessage("§c§oYou are already on the first page.");
                        return;
                    }
                    pagination.inventory().open(player, pagination.previous().page());
                }));

                int page = pagination.page() + 1;
                contents.set(5, 5, IntelligentItem.of(new ItemStack(Material.ARROW), event -> {
                    if (pagination.isLast()) {
                        player.sendMessage("§c§oYou are already on the last page.");
                        return;
                    }
                    pagination.inventory().open(player, pagination.next().page());
                }));

            }
        }).build(this);
    }

}
```

![Screenshot 2023-05-30 154646](https://github.com/RyseInventory/RyseInventory/assets/104507238/230353d7-4a34-4e86-ab11-341295ac1437)

**Comment by Rysefoxx** [comment]
What version of RyseInventory are you using?

**Comment by ch4ika** [comment]
The latest I just liked that you have a RyseInventoryExample and it doesn't work there either.
`
https://github.com/RyseInventory/RyseInventoryExample/blob/master/Minecraft/src/main/java/io/github/rysefoxx/example/command/InventoryCommand.java`

**Comment by Rysefoxx** [comment]
Okay funny, I'll definitely look over again and recreate your case with me.

**Comment by Rysefoxx** [comment]
Try with new version
https://github.com/RyseInventory/RyseInventory/releases/tag/v1.6.3
